name: Interesting things 
pygments: true
github: https://www.github.com/tcarrill
about: I am a software engineer with an interest in machine learning and general computer science theory.
urls:
    - text: github
      url: https://github.com/tcarrill
