# Dependencies
markdown:         kramdown 
highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            tc
tagline:          'Interesting things and stuff'
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Thomas Carrill'
  url:            http://thomas.moonlab.org

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           http://github.com/tcarrill

gems: [jekyll-paginate]